<a href="https://colab.research.google.com/github/bruguioti/Pytorch-Tutorial/blob/main/np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Tensors**

In [7]:
import torch
import numpy as np

## **Lists**

In [2]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

## **NUMPY ARRAYS**

In [8]:
np1 = np.random.rand(3,4)
np1

array([[0.37207702, 0.12309193, 0.11720184, 0.93002398],
       [0.90534337, 0.12545506, 0.08308743, 0.28451951],
       [0.54370908, 0.5781178 , 0.33822275, 0.8311931 ]])

In [9]:
np1.dtype

dtype('float64')

## **TENSORS**

In [10]:
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.8365, 0.6898, 0.6703, 0.0300],
        [0.6425, 0.7093, 0.9744, 0.4115],
        [0.1428, 0.3580, 0.4395, 0.7600]])

In [11]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
## Create tensor out numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.3721, 0.1231, 0.1172, 0.9300],
        [0.9053, 0.1255, 0.0831, 0.2845],
        [0.5437, 0.5781, 0.3382, 0.8312]], dtype=torch.float64)